
FROM node:18-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN corepack enable pnpm && pnpm i --frozen-lockfile

FROM base AS dev
WORKDIR /app


COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN corepack enable pnpm


RUN pnpm db:generate

EXPOSE 3000

ENV PORT 3000

CMD ["pnpm", "dev"]
